#' Trial with HTML stimulus and button response
#'
#' @param stimulus A stimulus object generated by stimulus_html()
#' @param response A response object generated by respond_button()
#' @param prompt The prompt to be displayed with the stimulus (can include HTML markup)
#' @param stimulus_duration How long to display stimulus in milliseconds? (default is to remain until response)
#' @param trial_duration How long to wait for response in milliseconds? (default is to wait indefinitely)
#' @param response_ends_trial Does the trial end with response (default = TRUE) or continue until trial duration reached?
#' @param ... Arguments to be passed to trial()
#' @export
trial_html_button <- function(
  stimulus,
  response,
  prompt = NULL,
  stimulus_duration = NULL,
  trial_duration = NULL,
  response_ends_trial = TRUE,
  ...
) {
  drop_nulls(
    trial(
      type = "html-keyboard-response",

      stimulus = stimulus,

      choices = response$choices,
      button_html = response$button_html,
      margin_vertical = response$margin_vertical,
      margin_horizontal = response$margin_horizontal,

      prompt = prompt,
      stimulus_duration = stimulus_duration,
      trial_duration = trial_duration,
      response_ends_trial = response_ends_trial
    )
  )
}

#' Trial with HTML stimulus and keyboard response
#'
#' @param stimulus A stimulus object generated by stimulus_html()
#' @param response A response object generated by respond_key()
#' @param prompt The prompt to be displayed with the stimulus (can include HTML markup)
#' @param stimulus_duration How long to display stimulus in milliseconds? (default is to remain until response)
#' @param trial_duration How long to wait for response in milliseconds? (default is to wait indefinitely)
#' @param response_ends_trial Does the trial end with response (default = TRUE) or continue until trial duration reached?
#' @param ... Arguments to be passed to trial()
#' @export
trial_html_key <- function(
  stimulus,
  response = respond_key("any"),
  prompt = NULL,
  stimulus_duration = NULL,
  trial_duration = NULL,
  response_ends_trial = TRUE,
  ...
) {
  drop_nulls(
    trial(
      type = "html-keyboard-response",

      stimulus = stimulus,

      choices = response$choices,

      prompt = prompt,
      stimulus_duration = stimulus_duration,
      trial_duration = trial_duration,
      response_ends_trial = response_ends_trial,
      ...
    )
  )
}

#' Trial with HTML stimulus and slider response
#'
#' @param stimulus A stimulus object generated by stimulus_html()
#' @param response A response object generated by respond_slider()
#' @param prompt The prompt to be displayed with the stimulus (can include HTML markup)
#' @param stimulus_duration How long to display stimulus in milliseconds? (default is to remain until response)
#' @param trial_duration How long to wait for response in milliseconds? (default is to wait indefinitely)
#' @param response_ends_trial Does the trial end with response (default = TRUE) or continue until trial duration reached?
#' @param ... Arguments to be passed to trial()
#' @export
trial_html_slider <- function(
  stimulus,
  response = respond_slider(),
  prompt = NULL,
  stimulus_duration = NULL,
  trial_duration = NULL,
  response_ends_trial = TRUE,
  ...
) {
  drop_nulls(
    trial(
      type = "html-slider-response",

      stimulus = stimulus,

      labels = response$labels,
      button_label = response$button_label,
      min = response$min,
      max = response$max,
      start = response$start,
      step = response$step,
      slider_width = response$slider_width,
      require_movement = response$require_movement,

      prompt = prompt,
      stimulus_duration = stimulus_duration,
      trial_duration = trial_duration,
      response_ends_trial = response_ends_trial,
      ...
    )
  )
}


