
# Wrapper functions for the following plugins:
#  - jspsych-survey-likert
#  - jspsych-survey-multi-choice
#  - jspsych-survey-multi-select
#  - jspsych-survey-text
#  - jspsych-survey-form ???


# post_trial_gap, on_finish, on_start, on_load, data

#' Define a Likert question
#'
#' @param prompt The question
#' @param labels The set of labels to attach to the Likert scale
#' @param required Is this a required question (default = FALSE)
#' @param name A name for the question (if NULL, defaults to Q0, Q1, etc)
#'
#' @export
question_likert <- function(prompt, labels, required = FALSE, name = NULL) {
  drop_nulls(
    js_struct(
      prompt = prompt, labels = labels, required = required, name = name
    )
  )
}

#' Define a multiple choice/selection question
#'
#' @param prompt The question
#' @param options The set of possible answers
#' @param required Is this a required question (default = FALSE)
#' @param horizontal Should the options be laid out horizontally (default = FALSE)
#' @param name A name for the question (if NULL, defaults to Q0, Q1, etc)
#'
#' @export
question_multi <- function(
  prompt, options, required = FALSE, horizontal = FALSE, name = NULL
) {
  drop_nulls(
    js_struct(
      prompt = prompt,
      options = options,
      required = required,
      horizontal = horizontal,
      name = name
    )
  )
}


#' Survey trial with Likert items
#'
#' @param questions A list of questions, each generated by question_likert()
#' @param randomize_question_order Should the question order be randomised? (default = FALSE)
#' @param preamble Text to display above the survey items
#' @param scale_width Width of the response scale in pixels (NULL defaults to max)
#' @param button_label Text displayed on button at the end (default = "Continue")
#'
#' @export
trial_survey_likert <- function(
  questions,
  randomize_question_order = FALSE,
  preamble = "",
  scale_width = NULL,
  button_label = "Continue"
) {
  drop_nulls(
    trial(
      type = "survey-likert",
      questions = list_to_jsarray(questions),
      randomize_question_order = as.logical(randomize_question_order),
      preamble = as.character(preamble),
      scale_width = scale_width,
      button_label = as.character(button_label)
    )
  )
}


#' Survey trial with multiple choice items
#'
#' @param questions A list of questions, each generated by question_multi_choice()
#' @param randomize_question_order Should the question order be randomised? (default = FALSE)
#' @param preamble Text to display above the survey items
#' @param button_label Text displayed on button at the end (default = "Continue")
#'
#' @export
trial_survey_multi_choice <- function(
  questions,
  randomize_question_order = FALSE,
  preamble = "",
  button_label = "Continue"
) {
  drop_nulls(
    trial(
      type = "survey-multi-choice",
      questions = list_to_jsarray(questions),
      randomize_question_order = as.logical(randomize_question_order),
      preamble = as.character(preamble),
      button_label = as.character(button_label)
    )
  )
}


#' Survey trial with multiple selection items
#'
#' @param questions A list of questions, each generated by question_multi_choice()
#' @param randomize_question_order Should the question order be randomised? (default = FALSE)
#' @param preamble Text to display above the survey items
#' @param button_label Text displayed on button at the end (default = "Continue")
#' @param required_message Text warning shown when a user does not select an option
#'
#' @export
trial_survey_multi_select <- function(
  questions,
  randomize_question_order = FALSE,
  preamble = "",
  button_label = "Continue",
  required_message = "You must choose at least one response for this question"
) {
  drop_nulls(
    trial(
      type = "survey-multi-select",
      questions = list_to_jsarray(questions),
      randomize_question_order = as.logical(randomize_question_order),
      preamble = as.character(preamble),
      button_label = as.character(button_label)
    )
  )
}





